TPF support for new developers survey
metacpan/metacpan-web pull request #2418
Opened 2021-01-05 15:45 UTC by andrewsolomon

This link needs to be removed at the end of January 2021

2021-01-05 15:51 UTC, oalders requested changes

2021-01-05 16:11 UTC, oalders approved these changes

2021-01-05 16:11 UTC, merged

2021-02-01 00:25 UTC, andrewsolomon commented
Is it ok if we leave this in until February 15? I figured it might be sensible to leave the survey open in case the FOSDEM talk generates more opinions...

2021-02-01 03:50 UTC, oalders commented
That sounds fine!